# Generated by Django 4.1.4 on 2022-12-08 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('SE', 'Services'), ('EL', 'Electronic'), ('EN', 'Energy'), ('LU', 'Luxury'), ('RE', 'Retail'), ('OT', 'Other')], default='OT', max_length=2)),
                ('siren', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.PositiveIntegerField()),
                ('margin', models.IntegerField()),
                ('ebitda', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='entreprises.entreprise')),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('entreprise', 'year'), name='unique_year_result'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(('year__lte', 2022)), name='year_lte_now'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 1980)), name='year_gte_1980'),
        ),
    ]
