# Generated by Django 4.1.4 on 2022-12-08 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_alter_entreprise_siren_alter_result_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='siren',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^/[0-9]{9}$', message='SIREN must be 9 digits')]),
        ),
    ]
