# Generated by Django 4.1.4 on 2022-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0007_alter_entreprise_siren_alter_result_ebitda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='sector',
            field=models.CharField(choices=[('Services', 'Services'), ('Electronic', 'Electronic'), ('Energy', 'Energy'), ('Luxury', 'Luxury'), ('Retail', 'Retail'), ('Other', 'Other')], default='Other', help_text='Choice (Services, Electronic, Energy, Luxury, Retail or Other)', max_length=10),
        ),
    ]
